# SPDX-FileCopyrightText: 2019-2020 Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "gb-cartpp-fwupd"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
build = "build.rs"

[[bin]]
name = "gb-cartpp-fwupd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = "2.33"
crc16 = "0.4"
gb-cartpp-fwupd-lib = { path = "../fwupd-lib" }
indicatif = "0.15"
itertools = "0.10"
log = "0.4"
simplelog = "0.9"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "gb-cartpp-fwupd.exe"
LegalCopyright = "Copyright © 2019-2020 Joonas Javanainen"
