# SPDX-FileCopyrightText: 2019-2022 Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = [
    "fwupd-cli",
    "fwupd-lib",
]
resolver = "2"

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1
